### ISSUE TITLE
ssq_dev -  wrong center calculation in oneclust.h

### ISSUE THREAD

**Issue by krzysztof-pankow** [nanxstats/oneclust#3]
It shouldn't be

`double center = sum(w * x) / sum(w);`

instead of:

`double center = sum(w * x) / x.length();`
?
Thanks for package anyway!

**Comment by nanxstats** [comment]
Great question. Here is an answer from ChatGPT:

> The correct calculation for the center of the points depends on how the weights are defined.
>
> If the weights are defined as frequency weights (i.e., each observation represents a certain number of occurrences), then the correct center of the points should be calculated as:
>
> ```cpp
> center = sum(w * x) / sum(w);
> ```
>
> This is because each observation with weight `w_i` contributes `w_i` times to the sum, so we need to divide the weighted sum by the total weight to get the weighted mean.
>
> On the other hand, if the weights are defined as sampling weights (i.e., each observation represents a certain proportion of the population), then the correct center of the points should be calculated as:
>
> ```cpp
> center = sum(w * x) / x.length();
> ```
>
> This is because each observation with weight `w_i` represents a certain proportion of the population, so we can treat each observation as equally important and take the unweighted mean.

So under our context, it should be `x.length()` as the documentation says "`w`: numeric vector, sample weights (optional)".

**Comment by krzysztof-pankow** [comment]
Ok, fair enough!
I would propose however to include somewhere "w = w/sum(w)" to allow for two types of weight input.
A user might not notice this distinction and, like me, get a wrong anwser.
Thank you!

**Comment by nanxstats** [comment]
Great, thanks for the suggestion. I clarified this important difference in https://github.com/nanxstats/oneclust/commit/8e53db7c52069e7426b719cc5fc8fbbedc29fcfc.

Having an unambiguous input would be ideal. Since one can always convert a frequency weight to a sampling weight easily but not the other way around, I'm going to stick with the original input format definition instead of allowing both.

I'm going to make a CRAN release.
